name: docker_mobile_backend
description: Backend Dart do Docker Mobile Admin.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  dart_jsonwebtoken: ^3.4.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
